name: Thông báo Lỗi
description: Tạo một báo cáo để cải thiện chất lượng dự án
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - duythanhvn
body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã dành thời gian giúp chúng tôi cải thiện chất lượng dự án này!
        
        Trước khi bạn tạo một Issue, vui lòng đảm bảo rằng bạn đã sử dụng phiên bản mới nhất của mã nguồn dự án cũng như thư viện đã cài đặt. Vui lòng xem thêm [tại đây](https://github.com/mlbvn/handson-ml2-vn/blob/main/install.md#c%E1%BA%ADp-nh%E1%BA%ADt-d%E1%BB%B1-%C3%A1n--c%C3%A1c-th%C6%B0-vi%E1%BB%87n-c%E1%BB%A7a-n%C3%B3).
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true